export const CREATE_DONOR_REQUEST = 'CREATE_DONOR_REQUEST';
export const CREATE_DONOR_SUCCESS = 'CREATE_DONOR_SUCCESS';
export const CREATE_DONOR_FAILURE = 'CREATE_DONOR_FAILURE';

export const GET_DONORS_REQUEST = 'GET_DONORS_REQUEST';
export const GET_DONORS_SUCCESS = 'GET_DONORS_SUCCESS';
export const GET_DONORS_FAILURE = 'GET_DONORS_FAILURE';